const ABSOLUTE_ROUTES = {
  AUTH: {
    ROOT: "/auth",
    REGISTER: "register",
    LOGIN: "login",
  },
  HOME: {
    ROOT: "/home",
  },
  TRAVEL_CALENDAR: {
    ROOT: "/travel-calendar",
  },
  TRAVEL_BOARD: {
    ROOT: "/travel-board",
  },
  ADD_ITINERARY: {
    ROOT: "/add-itinerary",
  },
};

export const ROUTES = {
  LOGIN_ROUTE: `${ABSOLUTE_ROUTES.AUTH.ROOT}/${ABSOLUTE_ROUTES.AUTH.LOGIN}`,
  REGISTER_ROUTE: `${ABSOLUTE_ROUTES.AUTH.ROOT}/${ABSOLUTE_ROUTES.AUTH.REGISTER}`,
  HOME_ROUTE: `${ABSOLUTE_ROUTES.HOME.ROOT}`,
  TRAVEL_CALENDAR: `${ABSOLUTE_ROUTES.TRAVEL_CALENDAR.ROOT}`,
  TRAVEL_BOARD: `${ABSOLUTE_ROUTES.TRAVEL_BOARD.ROOT}`,
  ADD_ITINERARY: `${ABSOLUTE_ROUTES.ADD_ITINERARY.ROOT}`,
};

export const PUBLIC_ROUTES = [ROUTES.LOGIN_ROUTE, ROUTES.REGISTER_ROUTE];
